Updating schema fields and sdk version
ConductorOne/baton-cloudflare pull request #19
Opened 2024-08-13 15:57 UTC by mchavez

- Updating schema fields and sdk version

2024-08-13 20:23 UTC, mgaeta requested changes

2024-08-13 20:23 UTC, mgaeta commented on cmd/baton-cloudflare/config.go
> +var (
```go
var (
	ApiKeyField = field.StringField(
		"api-key",
		field.WithDescription("The api key for the Cloudflare account."),
	)
	ApiTokenField = field.StringField(
		"api-token",
		field.WithDescription("The api token for the Cloudflare account."),
	)
	AccountIdField = field.StringField(
		"account-id",
		field.WithDescription("The account id for the Cloudflare account."),
		field.WithRequired(true),
	)
	EmailIdField = field.StringField(
		"email-id",
		field.WithDescription("The email id for the Cloudflare account."),
	)
	configurationFields = []field.SchemaField{
		ApiKeyField,
		ApiTokenField,
		AccountIdField,
		EmailIdField,
	}
	fieldRelationships = []field.SchemaFieldRelationship{
		field.FieldsAtLeastOneUsed(
			ApiTokenField,
			ApiKeyField,
		),
		field.FieldsDependentOn(
			[]field.SchemaField{
				ApiKeyField,
			},
			[]field.SchemaField{
				EmailIdField,
			},
		),
	}
)
```

2024-08-14 16:46 UTC, mgaeta commented on pkg/connector/connector.go
> +func New(ctx context.Context, cfg *viper.Viper) (*Cloudflare, error) {
Keep the original method signature.

2024-08-15 18:57 UTC, mchavez commented on pkg/connector/connector.go
> +func New(ctx context.Context, cfg *viper.Viper) (*Cloudflare, error) {
Fixed

2024-08-15 18:57 UTC, mchavez commented on cmd/baton-cloudflare/config.go
> +var (
Fixed

2024-08-15 19:04 UTC, mgaeta requested changes

2024-08-15 19:04 UTC, mgaeta commented on cmd/baton-cloudflare/main.go
> +	emailIdField        = field.StringField(connector.EmailId, field.WithRequired(true), field.WithDescription("The email id for the Cloudflare account."))
`emailIdField` should not be required.

```go
EmailIdField = field.StringField(
  "email-id",
  field.WithDescription("The email id for the Cloudflare account."),
)
```

2024-08-15 19:23 UTC, mchavez commented on cmd/baton-cloudflare/main.go
> +	emailIdField        = field.StringField(connector.EmailId, field.WithRequired(true), field.WithDescription("The email id for the Cloudflare account."))
Fixed

2024-08-15 19:24 UTC, mgaeta approved these changes

2024-08-20 19:47 UTC, ggreer commented on cmd/baton-cloudflare/main.go
> +		AccountId: cfg.GetString(accountId),
```suggestion
		AccountId: cfg.GetString(accountIdField.FieldName),
```
You can use `.FieldName` for all of these, allowing you to put the actual names in the calls to `field.StringField(...)` and delete the consts on lines 33-40.

2024-08-20 19:52 UTC, ggreer commented
Weird that CI is failing. This branch fetches the same resources as master, but I guess something changed in cloudflare so that we're not seeing the grant anymore. I think clean up the extra variables and this is good to go.

2024-09-03 20:17 UTC, mgaeta commented
@mchavez Can I close this PR?

2024-09-03 20:58 UTC, merged